version: "3.9"
services:
  frontend:
    build:
      context: ./static  # Path to your frontend directory
    ports:
      - "8080:80"
    volumes:
      - ./static:/usr/share/nginx/html  # Mount frontend files into the container
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Path to your backend directory
    ports:
      - "8000:8000"  # FastAPI runs on port 8000
    volumes:
      - ./backend:/app  # Mount backend code
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
