version: "3.9"
services:
  frontend:
    build:
      context: ./static
    ports:
      - "8080:80"
    volumes:
      - ./static:/usr/share/nginx/html
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app       # Bind mount for local development
      - my_backend_data:/data    # Volume for persistent data
    networks:
      - app-network

volumes:
  my_backend_data:  # Defines the volume "my_backend_data"
    driver: local   # Default driver for local volumes

networks:
  app-network:
    driver: bridge
